package com;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddToCartTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void addToCart() {
 driver.get("https://lifemobile.lk/");
 driver.manage().window().setSize(new Dimension(1600, 860));
 driver.findElement(By.linkText("Anker")).click();
 driver.findElement(By.cssSelector(".product:nth-child(2) .attachment-woocommerce_thumbnail")).click();
 driver.findElement(By.id("pa_select-warranty")).click();
 driver.findElement(By.id("pa_select-warranty")).click();
 driver.findElement(By.id("quantity_63b82119a9052")).click();
 driver.findElement(By.id("quantity_63b82119a9052")).click();
 driver.findElement(By.id("quantity_63b82119a9052")).sendKeys("2");
 driver.findElement(By.id("quantity_63b82119a9052")).click();
 driver.findElement(By.id("quantity_63b82119a9052")).sendKeys("3");
 driver.findElement(By.id("quantity_63b82119a9052")).click();
 driver.findElement(By.cssSelector(".single_add_to_cart_button")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".header-icon > .dropdown-toggle"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 {
   WebElement element = driver.findElement(By.cssSelector(".header-icon > .dropdown-toggle"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 driver.findElement(By.cssSelector(".dropdown-toggle > .cart-items-count")).click();
 driver.findElement(By.linkText("View cart")).click();
 driver.findElement(By.id("shipping_method_0_local_pickup12")).click();
 {
   WebElement element = driver.findElement(By.id("shipping_method_0_local_pickup12"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 driver.findElement(By.linkText("×")).click();
 driver.findElement(By.linkText("Return to shop")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".product:nth-child(2) .button"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
}
}
