package com;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WishlistTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void wishlist() {
 driver.get("https://lifemobile.lk/");
 driver.manage().window().setSize(new Dimension(1600, 860));
 driver.findElement(By.linkText("Dell")).click();
 driver.findElement(By.cssSelector(".product:nth-child(1) .attachment-woocommerce_thumbnail")).click();
 driver.findElement(By.cssSelector(".electro-wc-product-gallery__image:nth-child(2) .attachment-shop_thumbnail")).click();
 driver.findElement(By.cssSelector(".electro-wc-product-gallery__image:nth-child(3) .attachment-shop_thumbnail")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".electro-wc-product-gallery__image:nth-child(4) .attachment-shop_thumbnail"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.cssSelector(".electro-wc-product-gallery__image:nth-child(4) .attachment-shop_thumbnail")).click();
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 driver.findElement(By.cssSelector(".electro-wc-product-gallery__image .wp-post-image")).click();
 driver.findElement(By.cssSelector(".add-to-wishlist-106960 span")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".add-to-wishlist-106960 span"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 driver.findElement(By.cssSelector(".ec-favorites")).click();
 driver.findElement(By.linkText("Edit title")).click();
 driver.findElement(By.name("wishlist_name")).click();
 driver.findElement(By.name("wishlist_name")).sendKeys("My wishlist on Dell Mouse");
 driver.findElement(By.cssSelector(".fa-check")).click();
 driver.findElement(By.linkText("×")).click();
 {
   WebElement element = driver.findElement(By.linkText("×"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 driver.findElement(By.cssSelector(".header-site-branding .img-header-logo")).click();
}
}
